### ISSUE TITLE
i106_data_stream.c compile errors

### ISSUE THREAD

**Issue by kylekeppler** [bbaggerman/irig106lib#10]
Is no Npcap or Lpcap a supported config? Does i106_data_stream.c do anything in that case?

I am getting some errors (windows, VS2017):

> Error	C2143	syntax error: missing ';' before '}'	irig106dll	i106_data_stream.c	792	

> Error (active)	E0136	struct "<unnamed>" has no field "uDestPort"	irig106dll	i106_data_stream.c	451	

> Error	C2039	'uDestPort': is not a member of 'SuI106Ch10NetHandle'	irig106dll	i106_data_stream.c	451	

> Error (active)	E1072	a declaration cannot have a label	irig106dll	i106_data_stream.c	701

**Comment by bbaggerman** [comment]
Yeah, I saw that bug and had fixed it but not pushed it. It is pushed now. No Npcap or Lpcap is a supported config I just hadn't tested that when I originally pushed the code. BTW, being able to read a PCAP and extract the streaming Ch 10 messages has been **real** handy!

**Comment by kylekeppler** [comment]
Yep, I have some python that does that with the dpkt module. It's nice to have.
