### ISSUE TITLE
gcc compilation error

### ISSUE THREAD

**Issue by Mipsters** [bbaggerman/irig106lib#23]
https://github.com/bbaggerman/irig106lib/blob/63c54cd6ef37acd0576b44e09e8245b58050120a/src/irig106ch10.c#L1689

this should be `const void *`, it gives an error while compiling on gcc

like its `.h` file
https://github.com/bbaggerman/irig106lib/blob/63c54cd6ef37acd0576b44e09e8245b58050120a/src/irig106ch10.h#L422

**Comment by adrien-lessard** [comment]
I have observed this issue as well.

**Comment by Mipsters** [comment]
@adrien-lessard apparently pr #27 fixes this issue

**Comment by bbaggerman** [comment]
OK, it took a while but I incorporated Adrien's GCC fixes. I don't use GCC that often. Mostly I just check occasionally to make sure things still compile and seem to function.
